# Copyright (c) 2022-present, IO Visor Project
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2022-present, IO Visor Project
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Main

permissions:
  contents: read
  security-events: write # Required by codeql task.

on: [workflow_dispatch]
jobs:
  macos_release_sanitizers:
    uses: ./.github/workflows/posix.yml
    with:
      arch: x86_64
      platform: macos-11
      build_type: RelWithDebInfo
      enable_sanitizers: true

  macos_debug:
    uses: ./.github/workflows/posix.yml
    with:
      arch: x86_64
      platform: macos-11
      build_type: Debug